# Essential Linear Algebra for Finance

## 2.4     Matrix Decomposition  
  - 2.4.1  Spectral Decomposition of a Symmetric Matrix  
  - 2.4.2  Similarity Transforms  
  - 2.4.3  Cholesky Decomposition  
  - 2.4.4  LU Decomposition  

In [1]:
from visualisations import *

### 2.4.1 Spectral Decomposition of a Symmetric Matrix  

A special relationship exists for a symmetric square matrix $\mathbf{A}$ called **spectral decomposition**. 

The eigenvalues of a matrix $\mathbf{A}$ are represented as a diagonal matrix $\mathbf{\Lambda}$ with the associated eigenvectors in $\mathbf{W}$.

$$\mathbf{AW} = \mathbf{W\Lambda}$$  

If the eigenvalues in $\mathbf{\Lambda}$ are distinct and non-zero, then the eigenvectors of $\mathbf{W}$ are linearly independent and $\mathbf{W}$ is invertible.  

$$\mathbf{A} = \mathbf{W\Lambda W^{-1}}$$  

Given the eigenvectors are normalised to have unit length $\mathbf{W}$ is considered orthogonal having the property $\mathbf{W^{-1}} = \mathbf{W^{\top}}$ allowing us to rewrite the expression as 

$$\mathbf{A} = \mathbf{W\Lambda W^{\top}}$$  

### 2.4.2 Similarity Transforms

The sum of the diagonal elements of a matrix is known as the *trace* denoted often as $\mathrm{tr}(A)$  

A similarity transform exists such that for any invertible matrix $\mathbf{P}$ with the same dimensions as $\mathbf{A}$ 

$$\mathrm{tr}(A) = \mathrm{tr}(P^{-1}AP)$$  

These **similar matrices** or **matrix invariants** have the same trace, eigenvalues, determinant and rank.  

Manipulating the expression from the previous section $\mathbf{A} = \mathbf{W \Lambda W^{-1}}$ with some algebra to get  
$$\mathbf{\Lambda} = \mathbf{W^{-1}AW}$$  

The diagonal elements of the square matrix $\mathbf{A}$ are equal to the sum of its eigenvalues.  
Notice that the sum of the eigenvalues of $\mathbf{V}$ is equal to the *total variance* and the sum of the eigenvalues of $\mathbf{C}$ is equal to the *dimension* of the matrix.

### 2.4.3 Cholesky Decomposition

A **Cholesky matrix** is a special type of matrix that exists for matrices that are positive semi-definite and acts like the square root of a matrix.  

- If a matrix has only zeros *below* the main diagonal it is called **upper triangular**  
- If a matrix has only zeros *above* the main diagonal it is called **lower triangular**  

A lower triangular square matrix $\mathbf{Q}$ exists for a symmetric matrix $\mathbf{A}$ that is positive definite such that  

$$\mathbf{A} = \mathbf{QQ^{\top}}$$

$\text{Example}$

Find the Cholesky matrix for  

$$\mathbf{A} = \begin{bmatrix} 1 & -1 \\ -1 & 2 \end{bmatrix}$$  

To solve we let $\mathbf{Q} = \begin{bmatrix} a & 0 \\ b & c \end{bmatrix}$ so  

$$\mathbf{A} = \begin{bmatrix} 1 & -1 \\ -1 & 2 \end{bmatrix} = \begin{bmatrix} a & 0 \\ b & c \end{bmatrix} \begin{bmatrix} a & b \\ 0 & c \end{bmatrix} = \begin{bmatrix} a^{2} & ab \\ ab & b^{2} + c^{2} \end{bmatrix}$$  

Solving for $a^{2} = 1$, $ab = -1$ and $b^{2} + c^{2} = 2$ gives four potential Cholesky matrices  

$\begin{bmatrix} 1 & 0 \\ -1 & 1 \end{bmatrix}$; $\begin{bmatrix} -1 & 0 \\ 1 & 1 \end{bmatrix}$; $\begin{bmatrix} 1 & 0 \\ -1 & -1 \end{bmatrix}$; and $\begin{bmatrix} -1 & 0 \\ 1 & -1 \end{bmatrix}$  

This is expanded to larger dimensions in the text but an important takeaway is that we find that multiplying any column of $\mathbf{Q}$ by $-1$ will return a Cholesky matrix.  

Find the Cholesky decomposition matrix of $\mathbf{A}$ using python  

$$\mathbf{A} = \begin{bmatrix} 1 & 2 & 0 & 3 \\ 2 & 13 & 9 & 12 \\ 0 & 9 & 13 & 8 \\ 3 & 12 & 8 & 30 \end{bmatrix}$$

In [2]:
import numpy as np

# Construct the matrix A with numpy
A = np.array([
    [1, 2, 0, 3],
    [2, 13, 9, 12],
    [0, 9, 13, 8],
    [3, 12, 8, 30]
])

# Check for positive definiteness by finding the eigenvalues and checking to see if they are all positive
lambdas_A = np.linalg.eigvals(A)

# Printing the result
print(f"The eigenvalues of A are: {lambdas_A}")

The eigenvalues of A are: [41.11208853 11.74974899  0.31161414  3.82654835]


In [3]:
# They are indeed all positive so we can perform a Cholesky decomposition
Q = np.linalg.cholesky(A)

# Printing the result
print("Cholesky matrix Q:\n", Q)
print()

# L is lower triangular so its eigenvalues are the diagonal elements but we can verify 
# Print the eigenvalues of the Cholesky decomposition
lambdas_Q = np.linalg.eigvals(Q)
print(f"The eigenvalues of the Choleskey decomposition matrix are {lambdas_Q}")

Cholesky matrix Q:
 [[1. 0. 0. 0.]
 [2. 3. 0. 0.]
 [0. 3. 2. 0.]
 [3. 2. 1. 4.]]

The eigenvalues of the Choleskey decomposition matrix are [4. 2. 3. 1.]


Notice the eigenvalues of $\mathbf{Q}$ are different than the eigenvalues for $\mathbf{A}$ and are not equal to the square root of $\mathbf{A}$'s eigenvalues.

### 2.4.4 LU Decomposition

While Cholesky decomposition is restricted to positive definite matrices, $\mathbf{LU}$ decomposition can be applied to a variety of square matrices.  


A square matrix $\mathbf{A}$ can be decomposed to form the product of a lower triangular matrix $\mathbf{L}$ and an upper triangular matrix $\mathbf{U}$ with the same dimensions as $\mathbf{A}$.

$\mathbf{A} = \mathbf{LU}$  

- The matrix does not need to be non-singular to have a $\mathbf{LU}$ decomposition.
- Non-singular matrices do not always have an $\mathbf{LU}$ decomposition.
- A matrix with rank *k* (the number of linearly independent rows/columns) has an $\mathbf{LU}$ decomposition if and only if the first *k* principal minors are non-zero.  

$\text{Example}$  

Find the $\mathbf{LU}$ decomposition of $\mathbf{A}$ when   

$\mathbf{A} = \begin{bmatrix} 1 & 2 & 0 & 1 \\ 2 & 2 & 2 & -3 \\ 0 & 1 & 3 & 8 \\ 1 & -1 & 8 & -2 \end{bmatrix}$  

The text uses an excel add in but I will use numpy to find $\mathbf{L}$ and $\mathbf{U}$.  

Note that an $\mathbf{LU}$ decomposition does not always exist for a square matrix, but the text notes that we can permute the rows or columns of $\mathbf{L}$ and $\mathbf{U}$ as an alternative.

http://en.wikipedia.org/wiki/LU_decomposition

In [4]:
import numpy as np
from scipy.linalg import lu

# Matrix A
A = np.array([[1, 2, 0, 1],
              [2, 2, 2, -3],
              [0, 1, 3, 8],
              [1, -1, 8, -2]])

# Perform LU decomposition
P, L, U = lu(A)

print("\nPermutation matrix P:")
print(P)

print("\nLower triangular matrix L:")
print(L)

print("\nUpper triangular matrix U:")
print(U)

# Check: A = P @ L @ U
print("\nReconstructed A (P @ L @ U):")
print(P @ L @ U)



Permutation matrix P:
[[0. 0. 0. 1.]
 [1. 0. 0. 0.]
 [0. 0. 1. 0.]
 [0. 1. 0. 0.]]

Lower triangular matrix L:
[[ 1.          0.          0.          0.        ]
 [ 0.5         1.          0.          0.        ]
 [ 0.         -0.5         1.          0.        ]
 [ 0.5        -0.5         0.38461538  1.        ]]

Upper triangular matrix U:
[[ 2.          2.          2.         -3.        ]
 [ 0.         -2.          7.         -0.5       ]
 [ 0.          0.          6.5         7.75      ]
 [ 0.          0.          0.         -0.73076923]]

Reconstructed A (P @ L @ U):
[[ 1.  2.  0.  1.]
 [ 2.  2.  2. -3.]
 [ 0.  1.  3.  8.]
 [ 1. -1.  8. -2.]]


This permutation matrix $\mathbf{P}$ is important for numerical stability and without it $\mathbf{A} = \mathbf{LU}$ does not always hold but it is always true that $\mathbf{PA} = \mathbf{LU}$ for some permutation matrix $\mathbf{P}$

In [5]:
L @ U

array([[ 2.,  2.,  2., -3.],
       [ 1., -1.,  8., -2.],
       [ 0.,  1.,  3.,  8.],
       [ 1.,  2.,  0.,  1.]])

Since this is a relatively simple example we can also find $\mathbf{L}$ and $\mathbf{U}$ without the permuation matrix by importing lu_factor and lu_solve from python's scipy library.

In [6]:
from scipy.linalg import lu_factor, lu_solve

lu, piv = lu_factor(A)

print("Combined LU matrix:")
print(lu)

n = A.shape[0]

# Find the triangular lower (tril) matrix L
L = np.tril(lu, k = -1) + np.eye(n)
# Find the triangular upper (triu) matrix U
U = np.triu(lu)

print("\nL:")
print(L)

print("\nU:")
print(U)

Combined LU matrix:
[[ 2.          2.          2.         -3.        ]
 [ 0.5        -2.          7.         -0.5       ]
 [ 0.         -0.5         6.5         7.75      ]
 [ 0.5        -0.5         0.38461538 -0.73076923]]

L:
[[ 1.          0.          0.          0.        ]
 [ 0.5         1.          0.          0.        ]
 [ 0.         -0.5         1.          0.        ]
 [ 0.5        -0.5         0.38461538  1.        ]]

U:
[[ 2.          2.          2.         -3.        ]
 [ 0.         -2.          7.         -0.5       ]
 [ 0.          0.          6.5         7.75      ]
 [ 0.          0.          0.         -0.73076923]]
