# Essential Linear Algebra for Finance

## 2.4     Matrix Decomposition  
  - 2.4.1  Spectral Decomposition of a Symmetric Matrix  
  - 2.4.2  Similarity Transforms  
  - 2.4.3  Cholesky Decomposition  
  - 2.4.4  LU Decomposition  

In [1]:
from visualisations import *

### 2.4.1 Spectral Decomposition of a Symmetric Matrix  

A special relationship exists for a symmetric square matrix $\mathbf{A}$ called **spectral decomposition**. 

The eigenvalues of a matrix $\mathbf{A}$ are represented as a diagonal matrix $\mathbf{\Lambda}$ with the associated eigenvectors in $\mathbf{W}$.

$$\mathbf{AW} = \mathbf{W\Lambda}$$  

If the eigenvalues in $\mathbf{\Lambda}$ are distinct and non-zero, then the eigenvectors of $\mathbf{W}$ are linearly independent and $\mathbf{W}$ is invertible.  

$$\mathbf{A} = \mathbf{W\Lambda W^{-1}}$$  

Given the eigenvectors are normalised to have unit length $\mathbf{W}$ is considered orthogonal having the property $\mathbf{W^{-1}} = \mathbf{W^{\top}}$ allowing us to rewrite the expression as 

$$\mathbf{A} = \mathbf{W\Lambda W^{\top}}$$  

### 2.4.2 Similarity Transforms

The sum of the diagonal elements of a matrix is known as the *trace* denoted often as $\mathrm{tr}(A)$  

A similarity transform exists such that for any invertible matrix $\mathbf{P}$ with the same dimensions as $\mathbf{A}$ 

$$\mathrm{tr}(A) = \mathrm{tr}(P^{-1}AP)$$  

These **similar matrices** or **matrix invariants** have the same trace, eigenvalues, determinant and rank.  

Manipulating the expression from the previous section $\mathbf{A} = \mathbf{W \Lambda W^{-1}}$ with some algebra to get  
$$\mathbf{\Lambda} = \mathbf{W^{-1}AW}$$  

The diagonal elements of the square matrix $\mathbf{A}$ is equal to the sum of its eigenvalues.  
Notice that the sum of the eigenvalues of $\mathbf{V}$ is equal to the *total variance* and the sum of the eigenvalues of $\mathbf{C}$ is equal to the *dimension* of the matrix.

### 2.4.3 Cholesky Decomposition

A **Cholesky matrix** is a special type of matrix that exists for matrices that are positive semi-definite and acts like the square root of a matrix.  

- If a matrix has only zeros *below* the main diagonal it is called **upper triangular**  
- If a matrix has only zeros *above* the main diagonal it is called **lower triangular**  

A lower triangular square matrix $\mathbf{Q}$ exists for a symmetric matrix $\mathbf{A}$ that is positive definite such that  

$$\mathbf{A} = \mathbf{QQ^{\top}}$$

$\text{Example}$

Find the Cholesky matrix for  

$$\mathbf{A} = \begin{bmatrix} 1 & -1 \\ -1 & 2 \end{bmatrix}$$  

To solve we let $\mathbf{Q} = \begin{bmatrix} a & 0 \\ b & c \end{bmatrix}$ so  

$$\mathbf{A} = \begin{bmatrix} 1 & -1 \\ -1 & 2 \end{bmatrix} = \begin{bmatrix} a & 0 \\ b & c \end{bmatrix} \begin{bmatrix} a & b \\ 0 & c \end{bmatrix} = \begin{bmatrix} a^{2} & ab \\ ab & b^{2} + c^{2} \end{bmatrix}$$  

Solving for $a^{2} = 1$, $ab = -1$ and $b^{2} + c^{2} = 2$ gives four potential Cholesky matrices  

$\begin{bmatrix} 1 & 0 \\ -1 & 1 \end{bmatrix}$; $\begin{bmatrix} -1 & 0 \\ 1 & 1 \end{bmatrix}$; $\begin{bmatrix} 1 & 0 \\ -1 & -1 \end{bmatrix}$; and $\begin{bmatrix} -1 & 0 \\ 1 & -1 \end{bmatrix}$  

This is expanded to larger dimensions in the text but an important takeaway is that we find that multiplying any column of $\mathbf{Q}$ by $-1$ will return a Cholesky matrix.  

Find the Cholesky matrix of $\mathbf{A}$ using python  
 
$$\mathbf{A} = \begin{bmatrix} 1 & 2 & 0 & 3 \\ 2 & 13 & 9 & 12 \\ 0 & 9 & 13 & 8 \\ 3 & 12 & 8 & 30 \end{bmatrix}$$

In [ ]:
import numpy as np

# Construct the matrix A with numpy
A = np.array([
    [1, 2, 0, 3],
    [2, 13, 9, 12],
    [0, 9, 13, 8],
    [3, 12, 8, 30]
])

# Check for positive definiteness by finding the eigenvalues and checking to see if they are all positive
lambdas_A = np.linalg.eigvals(A)

# Printing the result
print(f"The eigenvalues of A are: {lambdas_A}")

The eigenvalues of A are: [41.11208853 11.74974899  0.31161414  3.82654835]


In [7]:
# They are indeed all positive so we can perform a Cholesky decomposition
Q = np.linalg.cholesky(A)

# Printing the result
print("Cholesky matrix Q:\n", Q)
print()

# L is lower triangular so its eigenvalues are the diagonal elements but we can verify 
# Print the eigenvalues of the Cholesky decomposition
lambdas_Q = np.linalg.eigvals(Q)
print(f"The eigenvalues of the Choleskey decomposition matrix are {lambdas_Q}")

Cholesky matrix Q:
 [[1. 0. 0. 0.]
 [2. 3. 0. 0.]
 [0. 3. 2. 0.]
 [3. 2. 1. 4.]]

The eigenvalues of the Choleskey decomposition matrix are [4. 2. 3. 1.]


Notice the eigenvalues of $\mathbf{Q}$ are different than the eigenvalues for $\mathbf{A}$ and are not equal to the square root of $\mathbf{A}$'s eigenvalues.

### 2.4.4 LU Decomposition